### ISSUE TITLE
Error: Cannot find module '../../services/authentication' with dash deploy

### ISSUE THREAD

**Issue by joelnet** [serverless/serverless-runtime-babel#14]
Everything runs fine when I run `sls function run authentication`. I get an error when trying to `sls dash deploy` my function.

inside my `handler.js` i have a line of code: `import authentication from '../../services/authentication';`

the exception I get when running `sls dash deploy` on my function is:

```
Error: Cannot find module '../../services/authentication' from 'C:\DEV\my-project\_meta\_tmp\auth-login@1460083275181'
    at C:\DEV\my-project\node_modules\resolve\lib\async.js:55:21
    at load (C:\DEV\my-project\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\DEV\my-project\node_modules\resolve\lib\async.js:92:31)
    at C:\DEV\my-project\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

My file structure is like this:

```
my-project/
    auth/
        login/
            handler.js
    services/
        authentication.js
```

**Comment by balmasi** [comment]
@joelnet  I don't think that's a `serverless-runtime-babel` issue.

but try this.

In your `s-function.json` file, change your `handler` attribute to `my-project/auth/login/handler.handler`  (or .default if exporting default)

since the path goes all the way up to `my-project` the auth and services folder dependencies automatically get deployed as well

**Comment by joelnet** [comment]
Thanks! changing the `handler` path to `auth/login/handler.handler` was the solution.

Though I am now experiencing this problem: https://github.com/serverless/serverless-runtime-babel/issues/13
